services:
  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql
      - ./dem_data:/dem_data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  web:
    build: .
    volumes:
      - .:/app
      - ./dem_data:/dem_data
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        sleep 5 &&
        python manage.py migrate &&
        python manage.py load_operational_dataset --run-all --dem-resolutions 300 --verbose &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_SETTINGS_MODULE: apexgps.settings
      OSM_URL: ${OSM_URL}
      OSM_URL_KUMI: ${OSM_URL_KUMI}
      OSM_URL_NCHC: ${OSM_URL_NCHC}
      OSM_URL_CH: ${OSM_URL_CH}
      LOCAL_PATH1: ${LOCAL_PATH1}
      LOCAL_PATH2: ${LOCAL_PATH2}
      REACT_SERVER: ${REACT_SERVER}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      INIT_AREA: italy
      NOMINATIM_URL: ${NOMINATIM_URL}
      PYTHONMALLOC: malloc
      MALLOC_ARENA_MAX: 2
      WIKIMEDIA_API_URL: ${WIKIMEDIA_API_URL}
      WIKIPEDIA_API_URL: ${WIKIPEDIA_API_URL}
      PIC4CARTO_API_URL: ${PIC4CARTO_API_URL}
      API_USER_AGENT: ${API_USER_AGENT}

volumes:
  pgdata: